
const KEY='metro_eats_v2';
const OLD_KEY='metro_eats_v1';
const categories={
 'Appetizers & Snacks':['Dips & Spreads','Finger Foods','Chips & Nachos','Wings','Charcuterie','Party Snacks'],
 'Breakfast & Brunch':['Eggs','Breakfast Meats','Pancakes & Waffles','French Toast','Biscuits & Gravy','Breakfast Casseroles','Brunch'],
 'Soups, Salads & Sandwiches':['Soups','Stews','Chili','Salads','Sandwiches','Burgers','Wraps'],
 'Main Dishes':['Beef','Pork','Chicken','Turkey','Seafood','Pasta','Casseroles','Meatless','Slow Cooker','One-Pot Meals'],
 'Mexican & Latin':['Tacos','Burritos','Enchiladas','Fajitas','Quesadillas','Nachos','Mexican Sides','Latin American'],
 'Italian':['Pasta','Pizza','Italian Beef','Chicken','Sauces','Italian Sides'],
 'BBQ & Grilling':['Steaks','Burgers','Ribs','Brisket','Pulled Pork','Chicken','Grilled Seafood','BBQ Sauces & Rubs'],
 'Side Dishes':['Potatoes','Rice','Vegetables','Mac & Cheese','Pasta Sides','Casseroles','Beans','Bread & Rolls'],
 'Sauces, Gravies & Condiments':['Sauces','Gravies','Marinades','Rubs','Dressings','Dips'],
 'Bread & Baking':['Breads','Biscuits','Rolls','Muffins','Cakes','Cookies','Pies','Pastries'],
 'Desserts':['Cakes','Pies','Cookies','Brownies & Bars','Ice Cream','Puddings','Fruit Desserts'],
 'Drinks':['Cocktails','Beer Drinks','Wine Drinks','Non-Alcoholic','Coffee','Tea','Smoothies & Shakes'],
 'Other':['Other']
};
const restaurantTypes=['American','Bar & Grill','BBQ','Burgers','Breakfast & Brunch','Cafés & Coffee','Chinese','Deli','Fast Food','Fine Dining','French','Indian','Italian','Japanese','Korean','Mediterranean','Mexican','Middle Eastern','Pizza','Seafood','Southern / Soul Food','Steakhouse','Thai','Vietnamese','Vegetarian / Vegan','Food Truck','Bakery','Dessert / Ice Cream','Brewery / Brewpub','Gastropub','Sports Bar','Other'];
const surveyQuestions=[['Overall Experience','Your overall impression of the visit.'],['Food Quality','Taste, freshness, preparation and consistency.'],['Menu & Selection','Variety, creativity and choices.'],['Service','Attentiveness, friendliness, professionalism and timing.'],['Atmosphere','Ambiance, comfort, noise level and vibe.'],['Cleanliness','Dining area, tables, restrooms and overall cleanliness.'],['Value for Money','Pricing, portions, quality and whether it felt worth it.'],['Drinks & Bar','Drink quality, selection, presentation and service.'],['Location & Accessibility','Parking, access, seating and convenience.'],['Would You Return?','How likely you are to return to this restaurant.']];
const fallbackNews=[
 {title:'10 St. Louis restaurants with great burgers',source:'Sauce Magazine',date:'October 1, 2026',url:'https://www.saucemagazine.com/'},
 {title:'St. Louis coffee shops roll out fall menus',source:'Sauce Magazine',date:'September 30, 2026',url:'https://www.saucemagazine.com/'},
 {title:'Heaterz is taking over Flock’s Downtown Alton property',source:'Sauce Magazine',date:'September 29, 2026',url:'https://www.saucemagazine.com/places-2/'},
 {title:'Oh London in Creve Coeur lands at No. 13 on Yelp’s Best New Restaurants of 2026 list',source:'St. Louis Magazine',date:'October 1, 2026',url:'https://www.stlmag.com/dining/'},
 {title:'The Fountain on Locust team to open Conefection at Wash Ave Food Hall',source:'St. Louis Magazine',date:'September 28, 2026',url:'https://www.stlmag.com/dining/'},
 {title:'Coffeestamp opens location in downtown St. Louis',source:'St. Louis Magazine',date:'September 25, 2026',url:'https://www.stlmag.com/dining/'},
 {title:'Heaterz Hot Chicken plans riverfront venue at Flock Food Truck site in Alton',source:'The Telegraph',date:'October 1, 2026',url:'https://www.thetelegraph.com/news/article/heaterz-hot-chicken-riverfront-alton-flock-truck-22454535.php'},
 {title:'Alton restaurant owner serves free steaks to striking public works union members',source:'The Telegraph',date:'October 2, 2026',url:'https://www.thetelegraph.com/news/article/alton-teamsters-strike-free-steaks-macs-downtown-22457126.php'},
 {title:'Vote now for your favorite local metro-east breakfast restaurant: Round 1',source:'Belleville News-Democrat',date:'September 29, 2026',url:'https://www.bnd.com/news/local/'}
];
const modal=document.getElementById('modal'),modalBody=document.getElementById('modalBody');let pendingRestaurant=null,pendingReviewRestaurant=null,restaurantEditMode=false,activeCat='',surveyState={restaurantId:null,scores:{},ordered:'',orderAgain:''};
function uid(){return 'me-'+Date.now().toString(36)+'-'+Math.random().toString(36).slice(2,10)}
function esc(s){return String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function save(){localStorage.setItem(KEY,JSON.stringify(db))}
function compressDataUrl(dataUrl,maxSide=1280,quality=.72){return new Promise(resolve=>{if(!/^data:image\//i.test(dataUrl||'')){resolve(dataUrl);return}let img=new Image();img.onload=()=>{let scale=Math.min(1,maxSide/Math.max(img.naturalWidth||img.width,img.naturalHeight||img.height)),w=Math.max(1,Math.round((img.naturalWidth||img.width)*scale)),h=Math.max(1,Math.round((img.naturalHeight||img.height)*scale)),canvas=document.createElement('canvas');canvas.width=w;canvas.height=h;let ctx=canvas.getContext('2d');ctx.drawImage(img,0,0,w,h);resolve(canvas.toDataURL('image/jpeg',quality))};img.onerror=()=>resolve(dataUrl);img.src=dataUrl})}
async function saveWithQuotaRecovery(){try{save();return}catch(e){if(e?.name!=='QuotaExceededError'&&e?.code!==22)throw e}let original=db.restaurants.map(r=>({...r,photos:[...(r.photos||[])]}));for(const r of db.restaurants){if(r.photos?.length)r.photos=await Promise.all(r.photos.map(p=>compressDataUrl(p,1280,.72)))}try{save();return}catch(e){db.restaurants=original;for(const r of db.restaurants){if(r.photos?.length)r.photos=await Promise.all(r.photos.map(p=>compressDataUrl(p,960,.58)))}try{save();return}catch(e2){db.restaurants=original;throw e2}}}

function fmtDateTime(v){if(!v)return '';let d=new Date(v);return Number.isNaN(d.getTime())?'':d.toLocaleString([], {year:'numeric',month:'short',day:'numeric',hour:'numeric',minute:'2-digit'})}
function stamp(label,v){return v?`<span class="timestamp"><strong>${esc(label)}:</strong> ${esc(fmtDateTime(v))}</span>`:''}
function fieldValue(id){return document.getElementById(id)?.value?.trim()||''}
function readFileAsDataUrl(file){return new Promise((resolve,reject)=>{let r=new FileReader();r.onload=()=>resolve(r.result);r.onerror=reject;r.readAsDataURL(file)})}
function parseData(){let raw=localStorage.getItem(KEY)||localStorage.getItem(OLD_KEY);if(!raw)return {recipes:[],restaurants:[]};try{return JSON.parse(raw)}catch{return {recipes:[],restaurants:[]}}}
let db=parseData();
function migrate(){const legacy={'Beef':['Main Dishes','Beef'],'Chicken':['Main Dishes','Chicken'],'Pork':['Main Dishes','Pork'],'Seafood':['Main Dishes','Seafood'],'Vegetables & Sides':['Side Dishes','Vegetables'],'Desserts':['Desserts','Cakes'],'Breakfast':['Breakfast & Brunch','Eggs']};db.recipes=(db.recipes||[]).map(r=>{let cat=categories[r.category]?r.category:(legacy[r.category]?.[0]||'Other'),sub=(categories[cat]||['Other']).includes(r.subcategory)?r.subcategory:(legacy[r.category]?.[1]||'Other');return {...r,id:r.id||uid(),category:cat,subcategory:sub,ingredients:r.ingredients||[],steps:r.steps||[],favorite:!!r.favorite,photos:r.photos||[],createdAt:r.createdAt||new Date().toISOString(),updatedAt:r.updatedAt||null}});db.restaurants=(db.restaurants||[]).map(r=>({...r,id:r.id||uid(),reviewHistory:r.reviewHistory||[],photos:r.photos||[],createdAt:r.createdAt||new Date().toISOString(),updatedAt:r.updatedAt||null}));db.cats=categories;save()}
migrate();
function tab(t){document.querySelectorAll('[data-tab]').forEach(b=>b.classList.toggle('active',b.dataset.tab===t));document.querySelectorAll('.section').forEach(s=>s.classList.toggle('active',s.id===t));if(t==='recipes')renderRecipes();if(t==='restaurants')renderRestaurants()}
document.querySelectorAll('[data-tab]').forEach(b=>b.addEventListener('click',()=>tab(b.dataset.tab)));
function renderCategoryFilter(){let e=document.getElementById('recipeCategoryFilter');if(!e)return;let v=e.value;e.innerHTML='<option value="">All Categories</option>'+Object.keys(categories).map(c=>`<option value="${esc(c)}">${esc(c)}</option>`).join('');e.value=categories[v]?v:''}
function filterRecipeCategory(c){activeCat=c;renderRecipes()}
function renderRecipes(){renderCategoryFilter();let q=(fieldValue('recipeSearch')).toLowerCase();let arr=db.recipes.filter(r=>(!activeCat||r.category===activeCat)&&(!q||JSON.stringify(r).toLowerCase().includes(q)));document.getElementById('recipeList').innerHTML=arr.length?arr.map(r=>`<article class="recipe" id="recipe-${r.id}"><div class="recipeHead clickable" onclick="toggleRecipe('${r.id}',event)"><div>${r.photos?.[0]?`<img class="recipePhoto" src="${esc(r.photos[0])}" alt="Photo of ${esc(r.title)}">`:''}<h3>${esc(r.title)} ${r.favorite?'★':''}</h3><div class="meta">${esc(r.category||'Other')} • ${esc(r.subcategory||'Other')} ${r.servings?'• '+esc(r.servings)+' servings':''} ${r.time?'• '+esc(r.time):''}</div>${stamp('Added',r.createdAt)}${r.updatedAt?stamp('Last updated',r.updatedAt):''}</div><div class="actions"><button class="btn" aria-label="Edit ${esc(r.title)}" onclick="event.stopPropagation();openRecipe('${r.id}')">Edit</button><button class="btn" aria-label="${r.favorite?'Remove from favorites':'Add to favorites'}" onclick="event.stopPropagation();toggleFav('${r.id}')">${r.favorite?'★':'☆'}</button></div></div><div class="recipeBody"><div><h4>Ingredients</h4><ul>${(r.ingredients||[]).map(x=>`<li>${esc(x)}</li>`).join('')}</ul></div><div><h4>Directions</h4><ol>${(r.steps||[]).map(x=>`<li>${esc(x)}</li>`).join('')}</ol></div></div></article>`).join(''):'<div class="empty">No recipes found.</div>'}
function toggleRecipe(id,e){if(e?.target?.closest('button'))return;document.getElementById('recipe-'+id)?.classList.toggle('expanded')}
function toggleFav(id){let r=db.recipes.find(x=>x.id===id);if(!r)return;r.favorite=!r.favorite;r.updatedAt=new Date().toISOString();save();renderRecipes();updateStory()}
function openRecipeChooser(){modal.classList.add('show');modalBody.innerHTML=`<div class="eyebrow">Your Kitchen</div><h2>Add a Recipe</h2><p class="hint">Choose how you want to start. Every path ends in the same recipe editor before anything is saved.</p><div class="choiceGrid"><article class="choiceCard"><div><div class="choiceIcon">✎</div><h3>Enter Manually</h3><p class="hint">Start with a blank Metro Eats recipe.</p></div><button class="btn primary" onclick="openRecipe('new')">Start Recipe</button></article><article class="choiceCard"><div><div class="choiceIcon">↗</div><h3>Import From Website</h3><p class="hint">Extract recipe-specific content from a public recipe page.</p></div><button class="btn primary" onclick="openWebsiteImporter()">Import Recipe</button></article><article class="choiceCard"><div><div class="choiceIcon">▤</div><h3>Paste Recipe</h3><p class="hint">Paste recipe text and let Metro Eats separate the useful parts.</p></div><button class="btn primary" onclick="openPasteImporter()">Paste Recipe</button></article></div><div class="actions"><button class="btn danger" onclick="closeModal()">Cancel</button></div>`}
function openRecipe(id,imported=null){let r=id==='new'?{id:'new',title:'',category:'Main Dishes',subcategory:'Beef',servings:'',time:'',ingredients:[],steps:[],favorite:false,createdAt:null,updatedAt:null,photos:[]}:db.recipes.find(x=>x.id===id);if(!r)return;modal.classList.add('show');modalBody.innerHTML=`<div class="eyebrow">Recipe editor</div><h2>${id==='new'?'Create Recipe':'Edit Recipe'}</h2><div class="fields"><div class="field full"><label for="fTitle">Recipe name</label><input id="fTitle" autocomplete="off" value="${esc(imported?.title??r.title)}"></div><div class="field"><label for="fCat">Category</label><select id="fCat" onchange="fillSubcats()">${Object.keys(categories).map(c=>`<option value="${esc(c)}" ${c===(imported?.category||r.category)?'selected':''}>${esc(c)}</option>`).join('')}</select></div><div class="field"><label for="fSub">Subcategory</label><select id="fSub"></select></div><div class="field"><label for="fServ">Servings</label><input id="fServ" value="${esc(imported?.servings??r.servings)}"></div><div class="field"><label for="fTime">Prep + cook time</label><input id="fTime" value="${esc(imported?.time??r.time)}"></div><div class="field full"><label for="fIng">Ingredients — one per line</label><textarea id="fIng" rows="9">${esc((imported?.ingredients||r.ingredients||[]).join('\n'))}</textarea></div><div class="field full"><label for="fSteps">Directions — one step per line</label><textarea id="fSteps" rows="9">${esc((imported?.steps||r.steps||[]).join('\n'))}</textarea></div><div class="field full"><label for="fPhoto">Recipe photo</label><input id="fPhoto" type="file" accept="image/*" capture="environment" onchange="previewRecipePhoto(this)"><div class="fileNote">Photos stay in your Metro Eats backup/export and are stored locally on this device.</div><div id="recipePhotoPreview"></div></div></div>${r.createdAt?stamp('Added',r.createdAt):''}${r.updatedAt?stamp('Last updated',r.updatedAt):''}<div class="actions"><button class="btn primary" onclick="saveRecipe('${id}')">Save Recipe</button><button class="btn danger" onclick="closeModal()">Cancel</button></div>`;window._recipePhoto=(imported?.photos?.[0]||r.photos?.[0]||'');renderRecipePhotoPreview();fillSubcats(imported?.subcategory||r.subcategory||'')}
function fillSubcats(selected=''){let c=document.getElementById('fCat')?.value,e=document.getElementById('fSub');if(!e)return;let opts=categories[c]||['Other'];e.innerHTML=opts.map(s=>`<option value="${esc(s)}" ${s===selected?'selected':''}>${esc(s)}</option>`).join('')}
async function previewRecipePhoto(input){if(input.files?.[0]){window._recipePhoto=await readFileAsDataUrl(input.files[0]);renderRecipePhotoPreview()}}
function renderRecipePhotoPreview(){let e=document.getElementById('recipePhotoPreview');if(!e)return;e.innerHTML=window._recipePhoto?`<img class="recipePhoto" src="${esc(window._recipePhoto)}" alt="Recipe photo preview"><button class="btn" onclick="window._recipePhoto='';renderRecipePhotoPreview()">Remove Photo</button>`:''}
function saveRecipe(id){let old=id==='new'?null:db.recipes.find(x=>x.id===id),now=new Date().toISOString(),r={id:id==='new'?uid():id,title:fieldValue('fTitle')||'Untitled Recipe',category:fieldValue('fCat'),subcategory:fieldValue('fSub'),servings:fieldValue('fServ'),time:fieldValue('fTime'),ingredients:fieldValue('fIng').split('\n').map(x=>x.trim()).filter(Boolean),steps:fieldValue('fSteps').split('\n').map(x=>x.trim()).filter(Boolean),favorite:old?.favorite||false,photos:window._recipePhoto?[window._recipePhoto]:[],createdAt:old?.createdAt||now,updatedAt:old?now:null};if(!r.ingredients.length||!r.steps.length)return alert('Please add ingredients and directions before saving.');if(id==='new')db.recipes.unshift(r);else db.recipes=db.recipes.map(x=>x.id===id?r:x);save();window._recipePhoto='';closeModal();renderRecipes();updateStory()}
function openWebsiteImporter(){modal.classList.add('show');modalBody.innerHTML=`<div class="eyebrow">Recipe importer</div><h2>Import From Website</h2><p class="hint">Metro Eats looks first for recipe structured data, then for clearly labeled Ingredients and Directions sections. Nothing is saved until you review it.</p><div class="field"><label for="recipeUrl">Recipe URL</label><input id="recipeUrl" type="url" inputmode="url" autocomplete="url" placeholder="https://example.com/recipe…"></div><div class="actions"><button class="btn primary" onclick="fetchWebsiteForCreateRecipe()">Import Recipe</button><button class="btn" onclick="openRecipeChooser()">← Back</button></div><div class="notice">Stories, nutrition, equipment, tips, ads, comments and unrelated page text are intentionally excluded.</div>`}
function openPasteImporter(){modal.classList.add('show');modalBody.innerHTML=`<div class="eyebrow">Recipe importer</div><h2>Paste Recipe</h2><p class="hint">Paste the recipe text. Metro Eats will look for the title, ingredients and directions and then let you review everything in the normal editor.</p><div class="field"><label for="rawRecipe">Recipe text</label><textarea id="rawRecipe" rows="15" placeholder="Paste the recipe here…"></textarea></div><div class="actions"><button class="btn primary" onclick="parsePastedRecipe()">Parse Recipe</button><button class="btn" onclick="openRecipeChooser()">← Back</button></div>`}
function cleanImportedLine(s){return String(s??'').replace(/<[^>]+>/g,' ').replace(/\[([^\]]+)\]\([^)]+\)/g,'$1').replace(/https?:\/\/\S+/gi,'').replace(/^\s*[-*•]\s*/,'').replace(/^\s*\d+[.)]\s*/,'').replace(/\s+/g,' ').trim()}
function isRecipeMetaLine(s){return /^(serves?|yield|yields|prep(?:aration)?\s*time|cook(?:ing)?\s*time|total\s*time|active\s*time|calories?|nutrition|author|by|jump to recipe|print recipe|save recipe|pin recipe|course|cuisine|keywords?)\b/i.test(String(s||'').trim())}
function isRecipeStopHeading(s){return /^(notes?|nutrition|nutritional information|calories?|more recipes|related recipes|you may also like|recommended|about the author|comments?|leave a reply|video|watch|equipment|tools|storage|variations?|tips?|substitutions?)\b/i.test(String(s||'').replace(/^#+\s*/,'').trim())}
function isBulletLine(s){return /^\s*(?:[-*•]|(?:\d+[.)]))\s+/.test(s)}
function normalizeRecipeInstruction(x){if(x==null)return '';if(typeof x==='string')return cleanImportedLine(x);if(typeof x==='object')return cleanImportedLine(x.text||x.name||'');return cleanImportedLine(x)}
function findRecipeJsonLd(html){let found=[];const re=/<script[^>]+type=["']application\/ld\+json["'][^>]*>([\s\S]*?)<\/script>/gi;let m;while((m=re.exec(html))){try{let raw=m[1].replace(/<!--|-->/g,'').trim();if(!raw)continue;let data=JSON.parse(raw);let walk=v=>{if(Array.isArray(v)){v.forEach(walk);return}if(v&&typeof v==='object'){let t=v['@type'];if((Array.isArray(t)?t:[t]).some(x=>String(x).toLowerCase()==='recipe'))found.push(v);if(v['@graph'])walk(v['@graph'])}};walk(data)}catch(e){}}return found[0]||null}
function structuredRecipeFromHtml(html,url){let r=findRecipeJsonLd(html);if(!r)return null;let ingredients=(r.recipeIngredient||[]).map(cleanImportedLine).filter(Boolean),instructions=[];let walk=v=>{if(Array.isArray(v)){v.forEach(walk);return}if(typeof v==='string'){let x=cleanImportedLine(v);if(x)instructions.push(x);return}if(v&&typeof v==='object'){if(v.itemListElement)walk(v.itemListElement);else if(v.text)walk(v.text);else if(v.name&&/howto(step|section)/i.test(String(v['@type']||'')))walk(v.name)}};walk(r.recipeInstructions);instructions=instructions.filter(x=>x.length<700);let time=[];if(r.prepTime)time.push('Prep '+cleanImportedLine(r.prepTime));if(r.cookTime)time.push('Cook '+cleanImportedLine(r.cookTime));if(!time.length&&r.totalTime)time.push('Total '+cleanImportedLine(r.totalTime));let servings=Array.isArray(r.recipeYield)?cleanImportedLine(r.recipeYield.join(', ')):cleanImportedLine(r.recipeYield||'');return ingredients.length&&instructions.length?{title:cleanImportedLine(r.name||''),ingredients:ingredients.slice(0,60),steps:instructions.slice(0,60),servings,time:time.join(' • ')}:null}
function collectSection(text,headingRegex){let lines=text.split(/\r?\n/).map(x=>x.trim()).filter(Boolean),start=lines.findIndex(x=>headingRegex.test(x.replace(/^#+\s*/,'')));if(start<0)return [];let out=[],seen=false;for(let i=start+1;i<lines.length;i++){let raw=lines[i];if(/^#+\s*/.test(raw)&&isRecipeStopHeading(raw))break;if(/^(ingredients?|directions?|instructions?|method|steps?)\s*:?$/i.test(raw))continue;if(isRecipeMetaLine(raw))continue;if(isBulletLine(raw))out.push(cleanImportedLine(raw));else if(out.length&&raw.length<500)out[out.length-1]+=' '+cleanImportedLine(raw);else if(!seen&&raw.length<250)out.push(cleanImportedLine(raw));seen=true}return out.filter(Boolean).slice(0,60)}
function extractRecipeCore(text,url){let title=(text.match(/<title[^>]*>([\s\S]*?)<\/title>/i)?.[1]||'').replace(/\s+/g,' ').trim();let ingredients=collectSection(text,/^(ingredients?)$/i),steps=collectSection(text,/^(directions?|instructions?|method|steps?)$/i);if(!ingredients.length||!steps.length)return null;return{title:title.replace(/\s*[|–-].*$/,'').trim()||'Imported Recipe',ingredients,steps,servings:'',time:''}}
async function fetchWebsiteForCreateRecipe(){let url=fieldValue('recipeUrl');if(!url)return alert('Please enter a recipe URL.');if(!/^https?:\/\//i.test(url))return alert('Please enter a full http:// or https:// recipe URL.');modalBody.innerHTML=`<div class="eyebrow">Recipe importer</div><h2>Extracting recipe…</h2><div class="status">Looking for recipe-specific structured data first.</div>`;try{let html='';try{let r=await fetch(url,{cache:'no-store'});if(r.ok)html=await r.text()}catch{}if(!html){let r=await fetch('https://r.jina.ai/'+url,{cache:'no-store'});if(!r.ok)throw Error();html=await r.text()}let parsed=structuredRecipeFromHtml(html,url)||extractRecipeCore(html,url);if(!parsed)throw Error('No clear recipe structure found');showImportedRecipeReview(parsed,'Website import')}catch(e){modalBody.innerHTML=`<div class="eyebrow">Recipe importer</div><h2>Couldn’t extract a clean recipe</h2><p class="hint">Metro Eats did not find enough clearly separated recipe content to safely import. Nothing was saved.</p><div class="actions"><button class="btn primary" onclick="openPasteImporter()">Paste Recipe Instead</button><button class="btn" onclick="openRecipeChooser()">Back</button></div>`}}
function parsePastedRecipe(){let text=fieldValue('rawRecipe');if(!text)return alert('Paste the recipe text first.');let lines=text.split(/\r?\n/).map(x=>x.trim()).filter(Boolean),title=lines[0]||'Pasted Recipe',ingredients=collectSection(text,/^(ingredients?)$/i),steps=collectSection(text,/^(directions?|instructions?|method|steps?)$/i);if(!ingredients.length||!steps.length){let mid=Math.max(1,Math.floor(lines.length/2));ingredients=ingredients.length?ingredients:lines.slice(1,mid).filter(x=>x.length<250).map(cleanImportedLine);steps=steps.length?steps:lines.slice(mid).filter(x=>x.length<500).map(cleanImportedLine)}showImportedRecipeReview({title,ingredients,steps,servings:'',time:''},'Pasted recipe')}
function showImportedRecipeReview(data,source){window._pendingImportedRecipe=data;modalBody.innerHTML=`<div class="eyebrow">${esc(source)}</div><h2>Review Before Saving</h2><p class="hint">This is an import preview. Review the extracted content, then continue into the normal recipe editor.</p><div class="status"><b>${esc(data.title||'Imported Recipe')}</b> • ${data.ingredients.length} ingredients • ${data.steps.length} directions</div><div class="fields"><div class="field full"><label>Extracted ingredients</label><textarea rows="7" readonly>${esc(data.ingredients.join('\n'))}</textarea></div><div class="field full"><label>Extracted directions</label><textarea rows="7" readonly>${esc(data.steps.join('\n'))}</textarea></div></div><div class="actions"><button class="btn primary" onclick="openRecipe('new',window._pendingImportedRecipe)">Continue to Recipe Editor</button><button class="btn danger" onclick="window._pendingImportedRecipe=null;closeModal()">Discard</button></div>`}
function openRestaurant(id,prefilling=null){let r=id==='new'?prefilling||{id:'new',name:'',type:'Other',location:'',website:'',menuUrl:'',notes:'',photos:[],survey:null,reviewHistory:[],createdAt:null,updatedAt:null}:db.restaurants.find(x=>x.id===id);if(!r)return;pendingRestaurant=id==='new'?{...r}:null;pendingReviewRestaurant=id==='new'?null:{...r,photos:[...(r.photos||[])]};restaurantEditMode=id!=='new';window._editingPhotos=[...(r.photos||[])];let latest=r.reviewHistory?.[r.reviewHistory.length-1]||r.survey||null;let scores=latest?.scores||{};surveyState={restaurantId:id==='new'?'new':id,scores:{},ordered:latest?.ordered||'',orderAgain:latest?.orderAgain||''};surveyQuestions.forEach((q,i)=>surveyState.scores[i]=Number((Array.isArray(scores)?scores[i]:scores[i])||0));renderSurvey()}
function continueRestaurantReview(id){return}
function cancelRestaurantWorkflow(){pendingRestaurant=null;pendingReviewRestaurant=null;restaurantEditMode=false;window._editingPhotos=[];closeModal()}
async function previewPhotos(input){let files=[...(input.files||[])];for(const file of files){window._editingPhotos.push(await readFileAsDataUrl(file))}let p=document.getElementById('photoPreview');if(p)p.innerHTML=window._editingPhotos.map((x,i)=>`<div><img src="${esc(x)}" alt="Meal photo ${i+1}"><button class="btn" onclick="removePhoto(${i})">Remove</button></div>`).join('')}
function removePhoto(i){window._editingPhotos.splice(i,1);let p=document.getElementById('photoPreview');if(p)p.innerHTML=window._editingPhotos.map((x,j)=>`<div><img src="${esc(x)}" alt="Meal photo ${j+1}"><button class="btn" onclick="removePhoto(${j})">Remove</button></div>`).join('')}
function useCurrentLocationForAddress(){if(!navigator.geolocation)return alert('Location services are not available in this browser.');let status=document.getElementById('rLoc');status.value='Finding your location…';navigator.geolocation.getCurrentPosition(async pos=>{try{let r=await fetch(`https://nominatim.openstreetmap.org/reverse?format=jsonv2&lat=${pos.coords.latitude}&lon=${pos.coords.longitude}&zoom=18&addressdetails=1`,{headers:{'Accept-Language':'en'}});let d=await r.json(),a=d.address||{},street=[a.house_number,a.road].filter(Boolean).join(' '),city=a.city||a.town||a.village||a.municipality||'',state=a.state_code||a.state||'';status.value=[street,city,state].filter(Boolean).join(', ')}catch{status.value=''}},()=>{status.value=''}, {enableHighAccuracy:true,timeout:12000,maximumAge:30000})}
function findWebsiteForCurrentRestaurant(){let q=encodeURIComponent(`${fieldValue('rName')} ${fieldValue('rLoc')} official restaurant website`);window.open('https://www.google.com/search?q='+q,'_blank','noopener')}
function findOfficialMenu(){let q=encodeURIComponent(`${fieldValue('rName')} ${fieldValue('rLoc')} official menu`);window.open('https://www.google.com/search?q='+q,'_blank','noopener')}
function officialMenuSearch(name,loc){return 'https://www.google.com/search?q='+encodeURIComponent(`${name} ${loc} official menu`)}
function renderRestaurants(){let q=fieldValue('restaurantSearch').toLowerCase(),arr=db.restaurants.filter(r=>JSON.stringify(r).toLowerCase().includes(q));document.getElementById('restaurantList').innerHTML=arr.length?arr.map(r=>restaurantCard(r)).join(''):'<div class="empty">No saved restaurants yet.</div>';updateStory()}
function restaurantCard(r){let s=r.survey,history=r.reviewHistory||[],summary=s?topRatedSummary(s):'';return `<article class="restaurant"><div class="recipeHead"><div><h3>${esc(r.name)}</h3><div class="meta">${esc(r.location||'')} ${r.type?'• '+esc(r.type):''}</div>${stamp('Added',r.createdAt)}${r.updatedAt?stamp('Last updated',r.updatedAt):''}</div><button class="btn" onclick="openRestaurant('${r.id}')">Edit</button></div>${s?`<div class="restaurantScoreCard" role="button" tabindex="0" onclick="showReviewDetails('${r.id}')" onkeydown="if(event.key==='Enter'||event.key===' '){event.preventDefault();showReviewDetails('${r.id}')}"><div><div class="restaurantScore">${Number(s.overall||0).toFixed(1)}<span style="font-size:.45em;letter-spacing:0"> / 10</span></div><div class="restaurantScoreLabel">Overall Experience</div></div><div><div class="topRated"><strong>Top Rated:</strong> ${summary||'Complete another visit for more detail.'}</div>${stamp('Reviewed',s.createdAt)}<div class="small" style="margin-top:8px">Tap to view the complete survey</div><div class="restaurantLinks"><button class="btn primary" onclick="event.stopPropagation();startSurvey('${r.id}')">Review Again</button><button class="btn" onclick="event.stopPropagation();showVisitHistory('${r.id}')">Visit History (${history.length})</button></div></div></div>`:`<div class="actions"><button class="btn primary" onclick="startSurvey('${r.id}')">★ Rate This Restaurant</button></div>`}${r.notes?`<p>${esc(r.notes)}</p>`:''}<div class="restaurantLinks">${r.website?`<a class="btn" href="${esc(r.website)}" target="_blank" rel="noopener noreferrer">Official Website</a>`:''}${r.menuUrl?`<a class="btn" href="${esc(r.menuUrl)}" target="_blank" rel="noopener noreferrer">Official Menu</a>`:`<a class="btn" href="${officialMenuSearch(r.name,r.location||'')}" target="_blank" rel="noopener noreferrer">Find Official Menu</a>`}</div>${r.photos?.length?`<div class="photos">${r.photos.slice(0,6).map((p,i)=>`<img src="${esc(p)}" alt="${esc(r.name)} meal photo ${i+1}">`).join('')}</div>`:''}</article>`}
function showReviewDetails(id){let r=db.restaurants.find(x=>x.id===id),s=r?.survey;if(!r||!s)return;modal.classList.add('show');modalBody.innerHTML='<div class="eyebrow">Complete Review</div><h2>'+esc(r.name)+'</h2><div class="meta">'+esc(r.location||'')+(r.type?' • '+esc(r.type):'')+'</div>'+stamp('Reviewed',s.createdAt)+'<div class="scoreHero"><div class="restaurantScore">'+Number(s.overall||0).toFixed(1)+'<span style="font-size:.45em;letter-spacing:0"> / 10</span></div><div class="restaurantScoreLabel">Overall Experience — 10-question survey</div></div><div class="reviewDetails">'+surveyQuestions.map((q,i)=>'<div class="reviewDetailRow"><div><b>'+(i+1)+'. '+esc(q[0])+'</b><div class="small">'+esc(q[1])+'</div></div><strong>'+Number(s.scores?.[i]||0)+'/10</strong></div>').join('')+'</div><div class="reviewExtras" style="margin-top:16px"><div class="field"><label>What did I eat?</label><div class="notice">'+esc(s.ordered||'Not recorded')+'</div></div><div class="field"><label>Would I order it again?</label><div class="notice">'+esc(s.orderAgain||'Not recorded')+'</div></div></div><div class="actions"><button class="btn primary" onclick="closeModal();startSurvey(\''+r.id+'\')">Edit Review</button><button class="btn danger" onclick="closeModal()">Close</button></div>'}
function topRatedSummary(s){let labels=surveyQuestions.map((q,i)=>({name:q[0],score:Number(s?.scores?.[i]||0),i})).filter(x=>x.i>0&&x.i<9&&x.score>0).sort((a,b)=>b.score-a.score).slice(0,3);return labels.map(x=>`${esc(x.name)} ${x.score}/10`).join(' • ')}
function findRestaurantAroundMe(){let status=document.getElementById('locationStatus');status.textContent='Requesting your location…';if(!navigator.geolocation){status.textContent='Location services are not available in this browser.';return}navigator.geolocation.getCurrentPosition(async pos=>{window._restaurantLookupLocation={lat:pos.coords.latitude,lon:pos.coords.longitude};status.textContent='Looking for restaurants near your location…';try{let lat=pos.coords.latitude,lon=pos.coords.longitude,q=`[out:json][timeout:12];(nwr[amenity=restaurant](around:300,${lat},${lon});nwr[amenity=fast_food](around:200,${lat},${lon}););out center tags;`,resp=await fetch('https://overpass-api.de/api/interpreter',{method:'POST',body:q});if(!resp.ok)throw Error();let data=await resp.json(),places=(data.elements||[]).map(x=>{let t=x.tags||{},la=x.lat??x.center?.lat,lo=x.lon??x.center?.lon;return{name:t.name||'',website:t.website||t['contact:website']||'',address:[t['addr:housenumber'],t['addr:street'],t['addr:city'],t['addr:state']].filter(Boolean).join(', '),lat:la,lon:lo,dist:Math.round(distanceMeters(lat,lon,la,lo))}}).filter(x=>x.name).sort((a,b)=>a.dist-b.dist).slice(0,10);renderNearby(places);status.textContent=places.length?'Select the restaurant that matches where you are.':'No named restaurants were found nearby. You can add it manually.'}catch{status.textContent='Could not query nearby restaurants. You can still add the restaurant manually.'}},()=>{status.textContent='Location permission was denied or unavailable.'},{enableHighAccuracy:true,timeout:12000,maximumAge:30000})}
function distanceMeters(a,b,c,d){if([a,b,c,d].some(x=>typeof x!=='number'))return 999999;let R=6371000,p=Math.PI/180,dLat=(c-a)*p,dLon=(d-b)*p,x=Math.sin(dLat/2)**2+Math.cos(a*p)*Math.cos(c*p)*Math.sin(dLon/2)**2;return 2*R*Math.asin(Math.sqrt(x))}
function renderNearby(places){let box=document.getElementById('nearbyResults');box.innerHTML=places.length?`<div class="locCard"><div class="eyebrow">Choose your restaurant</div><h3>Restaurants Around Me</h3><div class="nearbyList">${places.map((x,i)=>`<div class="nearbyItem"><strong>${esc(x.name)}</strong><div class="meta">${x.dist<1609?(Math.round(x.dist*3.28084)+' ft'):(x.dist/1609.34).toFixed(1)+' mi'} ${x.address?'• '+esc(x.address):''}</div><div class="actions"><button class="btn primary" onclick='useNearby(${JSON.stringify(x).replace(/'/g,"&#39;")})'>Select This Restaurant</button></div></div>`).join('')}</div></div>`:''}
function useNearby(x){pendingRestaurant={id:'new',name:x.name,type:'Other',location:x.address||'',website:x.website||'',menuUrl:'',notes:'',photos:[],survey:null,reviewHistory:[],createdAt:new Date().toISOString(),updatedAt:null};pendingReviewRestaurant=null;restaurantEditMode=false;window._editingPhotos=[];surveyState={restaurantId:'new',scores:{},ordered:'',orderAgain:''};renderSurvey()}
function currentSurveyRestaurant(){return pendingRestaurant||pendingReviewRestaurant||db.restaurants.find(x=>x.id===surveyState.restaurantId)}
function startSurvey(id){let r=db.restaurants.find(x=>x.id===id);if(!r)return;pendingRestaurant=null;pendingReviewRestaurant={...r,photos:[...(r.photos||[])]};restaurantEditMode=false;window._editingPhotos=[...(r.photos||[])];let latest=r.reviewHistory?.[r.reviewHistory.length-1]||r.survey||null;let priorScores=latest?.scores||{};surveyState={restaurantId:id,scores:{},ordered:latest?.ordered||'',orderAgain:latest?.orderAgain||''};surveyQuestions.forEach((q,i)=>{let v=Array.isArray(priorScores)?priorScores[i]:priorScores[i];surveyState.scores[i]=Number(v||0)});renderSurvey()}
function renderRestaurantEditor(r){return '<div class="eyebrow">'+(pendingRestaurant?'Dining capture':'Restaurant editor')+'</div><h2>'+(pendingRestaurant?'Create Restaurant & Review':'Edit Restaurant & Review')+'</h2><div class="fields"><div class="field full"><label for="rName">Restaurant name</label><input id="rName" value="'+esc(r?.name||'')+'" autocomplete="organization" oninput="restaurantNameChanged(this.value)"><div id="restaurantLookupResults"></div></div><div class="field"><label for="rType">Restaurant type</label><select id="rType">'+restaurantTypes.map(x=>'<option '+(x===(r?.type||'Other')?'selected':'')+'>'+esc(x)+'</option>').join('')+'</select></div><div class="field"><label for="rLoc">Street + city + state</label><input id="rLoc" value="'+esc(r?.location||'')+'" placeholder="123 Main St, Alton, IL"><div class="fileNote">Only street, city and state are shown in Metro Eats.</div></div><div class="field full"><label for="rWebsite">Official website</label><input id="rWebsite" type="url" inputmode="url" autocomplete="url" value="'+esc(r?.website||'')+'" placeholder="https://…"></div><div class="field full"><label for="rMenuUrl">Official menu</label><input id="rMenuUrl" type="url" inputmode="url" value="'+esc(r?.menuUrl||'')+'" placeholder="https://…"></div><div class="field full"><label for="rNotes">Notes</label><textarea id="rNotes" rows="3">'+esc(r?.notes||'')+'</textarea></div><div class="field full"><label for="rPhoto">Meal photos</label><input id="rPhoto" type="file" accept="image/*" multiple onchange="captureSurveyExtras();previewPhotos(this)"><div id="photoPreview" class="photos">'+window._editingPhotos.map((p,i)=>'<div><img src="'+esc(p)+'" alt="Meal photo '+(i+1)+'"><button class="btn" onclick="removePhoto('+i+')">Remove</button></div>').join('')+'</div></div></div><div class="actions"><button class="btn secondary" onclick="useCurrentLocationForAddress()">⌖ Use My Location</button><button class="btn" onclick="findWebsiteForCurrentRestaurant()">Find Official Website</button><button class="btn" onclick="findOfficialMenu()">Find Official Menu</button></div>'}
let restaurantLookupTimer=null,restaurantLookupRequest=0;
function normalizeRestaurantName(s){return String(s||'').toLowerCase().replace(/[’']/g,'').replace(/[^a-z0-9]+/g,' ').trim()}
function restaurantTypeFromLookup(t){let a=String(t?.amenity||'').toLowerCase(),c=String(t?.cuisine||'').toLowerCase();if(a==='cafe')return 'Cafés & Coffee';if(a==='bar'||a==='pub')return a==='pub'?'Gastropub':'Bar & Grill';if(c.includes('pizza'))return 'Pizza';if(c.includes('mexican')||c.includes('taco'))return 'Mexican';if(c.includes('italian'))return 'Italian';if(c.includes('indian'))return 'Indian';if(c.includes('japanese')||c.includes('sushi'))return 'Japanese';if(c.includes('chinese'))return 'Chinese';if(c.includes('thai'))return 'Thai';if(c.includes('korean'))return 'Korean';if(c.includes('vietnamese'))return 'Vietnamese';if(c.includes('seafood'))return 'Seafood';if(c.includes('steak'))return 'Steakhouse';if(c.includes('bbq')||c.includes('barbecue'))return 'BBQ';if(c.includes('burger'))return 'Burgers';if(c.includes('breakfast')||c.includes('brunch'))return 'Breakfast & Brunch';if(a==='fast_food')return 'Fast Food';if(a==='restaurant')return 'American';return 'Other'}
function lookupAddressFromResult(x){let a=x.address||{},street=[a.house_number,a.road].filter(Boolean).join(' '),city=a.city||a.town||a.village||a.municipality||'',state=a.state_code||a.state||'';return [street,city,state].filter(Boolean).join(', ')}
function restaurantSearchDistance(lat,lon){let p=window._restaurantLookupLocation;if(!p)return null;return Math.round(distanceMeters(p.lat,p.lon,Number(lat),Number(lon)))}
function dedupeRestaurantLookup(items){let seen=new Set();return items.filter(x=>{let k=normalizeRestaurantName(x.name)+'|'+(x.address||'');if(!x.name||seen.has(k))return false;seen.add(k);return true})}
function rankRestaurantLookup(a,q){let n=normalizeRestaurantName(a.name),qq=normalizeRestaurantName(q);return n===qq?0:n.startsWith(qq)?1:n.includes(qq)?2:3}
async function searchRestaurantLookup(q,requestId){let name=q.trim(),results=[];try{let local=window._restaurantLookupLocation;if(local){for(const miles of [2,5,15,30]){let radius=Math.round(miles*1609.344),safe=name.replaceAll('\\','\\\\').replaceAll('"','\\\"'),query='[out:json][timeout:10];nwr["name"~"'+safe+'",i](around:'+radius+','+local.lat+','+local.lon+');out center tags;',resp=await fetch('https://overpass-api.de/api/interpreter',{method:'POST',body:query});if(!resp.ok)continue;let data=await resp.json();results=(data.elements||[]).map(x=>{let t=x.tags||{},lat=x.lat??x.center?.lat,lon=x.lon??x.center?.lon;return{name:t.name||'',address:[t['addr:housenumber'],t['addr:street'],t['addr:city'],t['addr:state']].filter(Boolean).join(', '),website:t.website||t['contact:website']||'',type:restaurantTypeFromLookup(t),lat,lon,dist:restaurantSearchDistance(lat,lon),source:'OpenStreetMap'}}).filter(x=>x.name);if(results.length)break}}if(!results.length){let u='https://photon.komoot.io/api/?q='+encodeURIComponent(name)+'&limit=12&lang=en'+(local?'&lat='+local.lat+'&lon='+local.lon:'');let resp=await fetch(u);if(resp.ok){let data=await resp.json();results=(data.features||[]).map(f=>{let p=f.properties||{},g=f.geometry?.coordinates||[],amenity=p.osm_value==='restaurant'?'restaurant':p.osm_value==='fast_food'?'fast_food':p.osm_value==='cafe'?'cafe':p.osm_value==='bar'?'bar':p.osm_value==='pub'?'pub':'';return{name:p.name||'',address:[p.housenumber,p.street,p.city||p.locality,p.state].filter(Boolean).join(', '),website:p.extra?.website||'',type:restaurantTypeFromLookup({amenity,cuisine:p.extra?.cuisine}),lat:Number(g[1]),lon:Number(g[0]),dist:restaurantSearchDistance(g[1],g[0]),source:'Photon / OpenStreetMap'}}).filter(x=>x.name)}}if(requestId!==restaurantLookupRequest)return;results=dedupeRestaurantLookup(results).sort((a,b)=>rankRestaurantLookup(a,name)-rankRestaurantLookup(b,name)||((a.dist||999999)-(b.dist||999999))).slice(0,8);renderRestaurantLookupResults(results)}catch{if(requestId===restaurantLookupRequest)renderRestaurantLookupResults([],'Search unavailable right now. You can still enter the restaurant manually.')}}
function restaurantNameChanged(value){clearTimeout(restaurantLookupTimer);let q=value.trim(),box=document.getElementById('restaurantLookupResults');if(!box)return;if(q.length<2){box.innerHTML='';return}box.innerHTML='<div class="notice" style="margin-top:8px">Searching nearby restaurant information…</div>';restaurantLookupTimer=setTimeout(()=>{let id=++restaurantLookupRequest;searchRestaurantLookup(q,id)},500)}
function renderRestaurantLookupResults(results,message=''){let box=document.getElementById('restaurantLookupResults');if(!box)return;if(message){box.innerHTML='<div class="notice" style="margin-top:8px">'+esc(message)+'</div>';return}if(!results.length){box.innerHTML='<div class="notice" style="margin-top:8px">No matching restaurant found online. Keep entering the name or continue manually.</div>';return}box.innerHTML='<div class="lookupResults" style="margin-top:8px"><div class="fileNote">Select the correct restaurant to fill available details.</div>'+results.map(x=>'<button type="button" class="btn" style="display:block;width:100%;text-align:left;margin-top:6px" onclick="applyRestaurantLookup('+JSON.stringify(x).replace(/'/g,"&#39;")+')"><strong>'+esc(x.name)+'</strong><br><span class="small">'+esc(x.address||'Address not listed')+(x.dist!=null?' • '+(x.dist<1609?(Math.round(x.dist*3.28084)+' ft'):(x.dist/1609.34).toFixed(1)+' mi'):'')+(x.website?' • Website available':'')+'</span></button>').join('')+'</div>'}
function applyRestaurantLookup(x){captureSurveyExtras();let current=pendingRestaurant||pendingReviewRestaurant||{},merged={...current,name:x.name||fieldValue('rName'),location:current.location||x.address||'',website:current.website||x.website||'',type:(current.type&&current.type!=='Other')?current.type:(x.type||'Other'),lat:current.lat??x.lat,lon:current.lon??x.lon};if(pendingRestaurant)pendingRestaurant={...pendingRestaurant,...merged};else if(pendingReviewRestaurant)pendingReviewRestaurant={...pendingReviewRestaurant,...merged};surveyState.restaurantId=merged.id||surveyState.restaurantId;renderSurvey()}
function openRestaurant(id,prefilling=null){let r=id==='new'?prefilling||{id:'new',name:'',type:'Other',location:'',website:'',menuUrl:'',notes:'',photos:[],survey:null,reviewHistory:[],createdAt:null,updatedAt:null}:db.restaurants.find(x=>x.id===id);if(!r)return;pendingRestaurant=id==='new'?{...r}:null;pendingReviewRestaurant=id==='new'?null:{...r,photos:[...(r.photos||[])]};restaurantEditMode=id!=='new';window._editingPhotos=[...(r.photos||[])];let latest=r.reviewHistory?.[r.reviewHistory.length-1]||r.survey||null;let scores=latest?.scores||{};surveyState={restaurantId:id==='new'?'new':id,scores:{},ordered:latest?.ordered||'',orderAgain:latest?.orderAgain||''};surveyQuestions.forEach((q,i)=>surveyState.scores[i]=Number((Array.isArray(scores)?scores[i]:scores[i])||0));renderSurvey()}
function continueRestaurantReview(id){return}
function cancelRestaurantWorkflow(){pendingRestaurant=null;pendingReviewRestaurant=null;restaurantEditMode=false;window._editingPhotos=[];closeModal()}
async function previewPhotos(input){let files=[...(input.files||[])];for(const file of files){window._editingPhotos.push(await readFileAsDataUrl(file))}let p=document.getElementById('photoPreview');if(p)p.innerHTML=window._editingPhotos.map((x,i)=>`<div><img src="${esc(x)}" alt="Meal photo ${i+1}"><button class="btn" onclick="removePhoto(${i})">Remove</button></div>`).join('')}
function removePhoto(i){window._editingPhotos.splice(i,1);let p=document.getElementById('photoPreview');if(p)p.innerHTML=window._editingPhotos.map((x,j)=>`<div><img src="${esc(x)}" alt="Meal photo ${j+1}"><button class="btn" onclick="removePhoto(${j})">Remove</button></div>`).join('')}
function useCurrentLocationForAddress(){if(!navigator.geolocation)return alert('Location services are not available in this browser.');let status=document.getElementById('rLoc');status.value='Finding your location…';navigator.geolocation.getCurrentPosition(async pos=>{try{let r=await fetch(`https://nominatim.openstreetmap.org/reverse?format=jsonv2&lat=${pos.coords.latitude}&lon=${pos.coords.longitude}&zoom=18&addressdetails=1`,{headers:{'Accept-Language':'en'}});let d=await r.json(),a=d.address||{},street=[a.house_number,a.road].filter(Boolean).join(' '),city=a.city||a.town||a.village||a.municipality||'',state=a.state_code||a.state||'';status.value=[street,city,state].filter(Boolean).join(', ')}catch{status.value=''}},()=>{status.value=''}, {enableHighAccuracy:true,timeout:12000,maximumAge:30000})}
function findWebsiteForCurrentRestaurant(){let q=encodeURIComponent(`${fieldValue('rName')} ${fieldValue('rLoc')} official restaurant website`);window.open('https://www.google.com/search?q='+q,'_blank','noopener')}
function findOfficialMenu(){let q=encodeURIComponent(`${fieldValue('rName')} ${fieldValue('rLoc')} official menu`);window.open('https://www.google.com/search?q='+q,'_blank','noopener')}
function officialMenuSearch(name,loc){return 'https://www.google.com/search?q='+encodeURIComponent(`${name} ${loc} official menu`)}
function renderRestaurants(){let q=fieldValue('restaurantSearch').toLowerCase(),arr=db.restaurants.filter(r=>JSON.stringify(r).toLowerCase().includes(q));document.getElementById('restaurantList').innerHTML=arr.length?arr.map(r=>restaurantCard(r)).join(''):'<div class="empty">No saved restaurants yet.</div>';updateStory()}
function restaurantCard(r){let s=r.survey,history=r.reviewHistory||[],summary=s?topRatedSummary(s):'';return `<article class="restaurant"><div class="recipeHead"><div><h3>${esc(r.name)}</h3><div class="meta">${esc(r.location||'')} ${r.type?'• '+esc(r.type):''}</div>${stamp('Added',r.createdAt)}${r.updatedAt?stamp('Last updated',r.updatedAt):''}</div><button class="btn" onclick="openRestaurant('${r.id}')">Edit</button></div>${s?`<div class="restaurantScoreCard"><div><div class="restaurantScore">${Number(s.overall||0).toFixed(1)}<span style="font-size:.45em;letter-spacing:0"> / 10</span></div><div class="restaurantScoreLabel">Overall Experience</div></div><div><div class="topRated"><strong>Top Rated:</strong> ${summary||'Complete another visit for more detail.'}</div>${stamp('Reviewed',s.createdAt)}<div class="restaurantLinks"><button class="btn primary" onclick="startSurvey('${r.id}')">Review Again</button><button class="btn" onclick="showVisitHistory('${r.id}')">Visit History (${history.length})</button></div></div></div>`:`<div class="actions"><button class="btn primary" onclick="startSurvey('${r.id}')">★ Rate This Restaurant</button></div>`}${r.notes?`<p>${esc(r.notes)}</p>`:''}<div class="restaurantLinks">${r.website?`<a class="btn" href="${esc(r.website)}" target="_blank" rel="noopener noreferrer">Official Website</a>`:''}${r.menuUrl?`<a class="btn" href="${esc(r.menuUrl)}" target="_blank" rel="noopener noreferrer">Official Menu</a>`:`<a class="btn" href="${officialMenuSearch(r.name,r.location||'')}" target="_blank" rel="noopener noreferrer">Find Official Menu</a>`}</div>${r.photos?.length?`<div class="photos">${r.photos.slice(0,6).map((p,i)=>`<img src="${esc(p)}" alt="${esc(r.name)} meal photo ${i+1}">`).join('')}</div>`:''}</article>`}
function topRatedSummary(s){let labels=surveyQuestions.map((q,i)=>({name:q[0],score:Number(s?.scores?.[i]||0),i})).filter(x=>x.i>0&&x.i<9&&x.score>0).sort((a,b)=>b.score-a.score).slice(0,3);return labels.map(x=>`${esc(x.name)} ${x.score}/10`).join(' • ')}
function findRestaurantAroundMe(){let status=document.getElementById('locationStatus');status.textContent='Requesting your location…';if(!navigator.geolocation){status.textContent='Location services are not available in this browser.';return}navigator.geolocation.getCurrentPosition(async pos=>{status.textContent='Looking for restaurants near your location…';try{let lat=pos.coords.latitude,lon=pos.coords.longitude,q=`[out:json][timeout:12];(nwr[amenity=restaurant](around:300,${lat},${lon});nwr[amenity=fast_food](around:200,${lat},${lon}););out center tags;`,resp=await fetch('https://overpass-api.de/api/interpreter',{method:'POST',body:q});if(!resp.ok)throw Error();let data=await resp.json(),places=(data.elements||[]).map(x=>{let t=x.tags||{},la=x.lat??x.center?.lat,lo=x.lon??x.center?.lon;return{name:t.name||'',website:t.website||t['contact:website']||'',address:[t['addr:housenumber'],t['addr:street'],t['addr:city'],t['addr:state']].filter(Boolean).join(', '),lat:la,lon:lo,dist:Math.round(distanceMeters(lat,lon,la,lo))}}).filter(x=>x.name).sort((a,b)=>a.dist-b.dist).slice(0,10);renderNearby(places);status.textContent=places.length?'Select the restaurant that matches where you are.':'No named restaurants were found nearby. You can add it manually.'}catch{status.textContent='Could not query nearby restaurants. You can still add the restaurant manually.'}},()=>{status.textContent='Location permission was denied or unavailable.'},{enableHighAccuracy:true,timeout:12000,maximumAge:30000})}
function distanceMeters(a,b,c,d){if([a,b,c,d].some(x=>typeof x!=='number'))return 999999;let R=6371000,p=Math.PI/180,dLat=(c-a)*p,dLon=(d-b)*p,x=Math.sin(dLat/2)**2+Math.cos(a*p)*Math.cos(c*p)*Math.sin(dLon/2)**2;return 2*R*Math.asin(Math.sqrt(x))}
function renderNearby(places){let box=document.getElementById('nearbyResults');box.innerHTML=places.length?`<div class="locCard"><div class="eyebrow">Choose your restaurant</div><h3>Restaurants Around Me</h3><div class="nearbyList">${places.map((x,i)=>`<div class="nearbyItem"><strong>${esc(x.name)}</strong><div class="meta">${x.dist<1609?(Math.round(x.dist*3.28084)+' ft'):(x.dist/1609.34).toFixed(1)+' mi'} ${x.address?'• '+esc(x.address):''}</div><div class="actions"><button class="btn primary" onclick='useNearby(${JSON.stringify(x).replace(/'/g,"&#39;")})'>Select This Restaurant</button></div></div>`).join('')}</div></div>`:''}
function useNearby(x){pendingRestaurant={id:'new',name:x.name,type:'Other',location:x.address||'',website:x.website||'',menuUrl:'',notes:'',photos:[],survey:null,reviewHistory:[],createdAt:new Date().toISOString(),updatedAt:null,lat:x.lat,lon:x.lon};pendingReviewRestaurant=null;restaurantEditMode=false;window._editingPhotos=[];surveyState={restaurantId:'new',scores:{},ordered:'',orderAgain:''};renderSurvey()}
function currentSurveyRestaurant(){return pendingRestaurant||pendingReviewRestaurant||db.restaurants.find(x=>x.id===surveyState.restaurantId)}
function startSurvey(id){let r=db.restaurants.find(x=>x.id===id);if(!r)return;pendingRestaurant=null;pendingReviewRestaurant={...r,photos:[...(r.photos||[])]};restaurantEditMode=false;window._editingPhotos=[...(r.photos||[])];let latest=r.reviewHistory?.[r.reviewHistory.length-1]||r.survey||null;let priorScores=latest?.scores||{};surveyState={restaurantId:id,scores:{},ordered:latest?.ordered||'',orderAgain:latest?.orderAgain||''};surveyQuestions.forEach((q,i)=>{let v=Array.isArray(priorScores)?priorScores[i]:priorScores[i];surveyState.scores[i]=Number(v||0)});renderSurvey()}
function renderRestaurantEditor(r){return `<div class="eyebrow">${pendingRestaurant?'Dining capture':'Restaurant editor'}</div><h2>${pendingRestaurant?'Create Restaurant & Review':'Edit Restaurant & Review'}</h2><div class="fields"><div class="field full"><label for="rName">Restaurant name</label><input id="rName" value="${esc(r?.name||'')}" autocomplete="organization" oninput="restaurantNameChanged(this.value)"><div id="restaurantLookupResults"></div></div><div class="field"><label for="rType">Restaurant type</label><select id="rType">${restaurantTypes.map(x=>`<option ${x===(r?.type||'Other')?'selected':''}>${esc(x)}</option>`).join('')}</select></div><div class="field"><label for="rLoc">Street + city + state</label><input id="rLoc" value="${esc(r?.location||'')}" placeholder="123 Main St, Alton, IL"><div class="fileNote">Only street, city and state are shown in Metro Eats.</div></div><div class="field full"><label for="rWebsite">Official website</label><input id="rWebsite" type="url" inputmode="url" autocomplete="url" value="${esc(r?.website||'')}" placeholder="https://…"></div><div class="field full"><label for="rMenuUrl">Official menu</label><input id="rMenuUrl" type="url" inputmode="url" value="${esc(r?.menuUrl||'')}" placeholder="https://…"></div><div class="field full"><label for="rNotes">Notes</label><textarea id="rNotes" rows="3">${esc(r?.notes||'')}</textarea></div><div class="field full"><label for="rPhoto">Meal photos</label><input id="rPhoto" type="file" accept="image/*" multiple onchange="captureSurveyExtras();previewPhotos(this)"><div id="photoPreview" class="photos">${window._editingPhotos.map((p,i)=>`<div><img src="${esc(p)}" alt="Meal photo ${i+1}"><button class="btn" onclick="removePhoto(${i})">Remove</button></div>`).join('')}</div></div></div><div class="actions"><button class="btn secondary" onclick="useCurrentLocationForAddress()">⌖ Use My Location</button><button class="btn" onclick="findWebsiteForCurrentRestaurant()">Find Official Website</button><button class="btn" onclick="findOfficialMenu()">Find Official Menu</button></div>`}
function renderSurvey(){let r=currentSurveyRestaurant(),name=r?.name||'Restaurant Review';if(!window._editingPhotos)window._editingPhotos=[...(r?.photos||[])];modal.classList.add('show');modalBody.innerHTML=`${renderRestaurantEditor(r)}<div class="status">Survey</div><div class="scoreHero"><div class="restaurantScore">${surveyAverage()||'—'}<span style="font-size:.45em;letter-spacing:0"> / 10</span></div><div class="restaurantScoreLabel">Overall Score — based on 10 ratings</div></div><div class="meta">${esc(name)}${r?.location?' • '+esc(r.location):''}</div><div class="reviewForm">${surveyQuestions.map((q,i)=>`<div class="reviewQuestion"><div class="reviewQuestionHead"><b>${i+1}. ${q[0]}</b><span>${surveyState.scores[i]?surveyState.scores[i]+'/10':'Select 1–10'}</span></div><div class="reviewScore">${[1,2,3,4,5,6,7,8,9,10].map(n=>`<button aria-label="${q[0]} score ${n}" class="${surveyState.scores[i]===n?'active':''}" onclick="setSurveyScore(${i},${n})">${n}</button>`).join('')}</div><div class="surveyScale"><span>Poor</span><span>Average</span><span>Exceptional</span></div></div>`).join('')}</div><div class="reviewExtras"><div class="field"><label for="surveyOrdered">What did I eat?</label><textarea id="surveyOrdered" class="surveyNote" rows="3" placeholder="What did you order?">${esc(surveyState.ordered)}</textarea></div><div class="field"><label>Would I order it again?</label><div class="actions"><button class="btn ${surveyState.orderAgain==='Yes'?'primary':''}" onclick="setOrderAgain('Yes')">Yes</button><button class="btn ${surveyState.orderAgain==='No'?'primary':''}" onclick="setOrderAgain('No')">No</button></div></div></div><div class="surveyActions"><button class="btn danger" onclick="cancelSurvey()">Cancel</button><button class="btn primary" onclick="saveSurvey()">${pendingRestaurant?'Save Restaurant & Review':'Save Restaurant & Review'}</button></div>`}
function surveyAverage(){let vals=surveyQuestions.map((q,i)=>Number(surveyState.scores[i]||0)).filter(v=>v>0);return vals.length?(Math.round(vals.reduce((a,b)=>a+b,0)/vals.length*10)/10).toFixed(1):''}
function setSurveyScore(i,n){captureSurveyExtras();surveyState.scores[i]=n;renderSurvey()}
function setOrderAgain(v){captureSurveyExtras();surveyState.orderAgain=v;renderSurvey()}
function captureSurveyExtras(){surveyState.ordered=document.getElementById('surveyOrdered')?.value?.trim()||surveyState.ordered}
async function saveSurvey(){captureSurveyExtras();let missing=surveyQuestions.findIndex((q,i)=>!surveyState.scores[i]);if(missing>=0){alert('Please choose a score from 1 to 10 for Question '+(missing+1)+'.');return}if(!surveyState.ordered){alert('Please tell us what you ate.');document.getElementById('surveyOrdered')?.focus();return}if(!surveyState.orderAgain){alert('Please choose Yes or No for whether you would order it again.');return}let now=new Date().toISOString(),review={scores:{...surveyState.scores},ordered:surveyState.ordered,orderAgain:surveyState.orderAgain,overall:Number(surveyAverage()),createdAt:now};let currentRestaurant=pendingRestaurant||pendingReviewRestaurant||{},restaurantFields={name:fieldValue('rName')||'Unnamed restaurant',type:fieldValue('rType')||'Other',location:fieldValue('rLoc'),website:fieldValue('rWebsite'),menuUrl:fieldValue('rMenuUrl'),notes:fieldValue('rNotes'),photos:[...(window._editingPhotos||[])],lat:currentRestaurant.lat??null,lon:currentRestaurant.lon??null};let saveButton=document.querySelector('.surveyActions .btn.primary');if(saveButton){saveButton.disabled=true;saveButton.textContent='Saving…'}try{if(pendingRestaurant){let r={...pendingRestaurant,...restaurantFields,reviewHistory:[review],survey:review,rating:Math.max(1,Math.min(5,Math.round(review.overall/2*10)/10)),createdAt:pendingRestaurant.createdAt||now,updatedAt:now};db.restaurants.unshift(r)}else if(pendingReviewRestaurant){let r=db.restaurants.find(x=>x.id===pendingReviewRestaurant.id);if(!r)throw new Error('The restaurant could not be found in your saved restaurants.');Object.assign(r,pendingReviewRestaurant,restaurantFields);if(restaurantEditMode&&r.reviewHistory?.length){r.reviewHistory=[...(r.reviewHistory||[]).slice(0,-1),review]}else{r.reviewHistory=[...(r.reviewHistory||[]),review]}r.survey=review;r.rating=Math.max(1,Math.min(5,Math.round(review.overall/2*10)/10));r.updatedAt=now}else{let r=db.restaurants.find(x=>x.id===surveyState.restaurantId);if(!r)throw new Error('The restaurant could not be found in your saved restaurants.');Object.assign(r,restaurantFields);r.reviewHistory=[...(r.reviewHistory||[]),review];r.survey=review;r.rating=Math.max(1,Math.min(5,Math.round(review.overall/2*10)/10));r.updatedAt=now}await saveWithQuotaRecovery();pendingRestaurant=null;pendingReviewRestaurant=null;restaurantEditMode=false;window._editingPhotos=[];closeModal();renderRestaurants();showRankings()}catch(e){console.error('Metro Eats saveSurvey failed',e);if(saveButton){saveButton.disabled=false;saveButton.textContent='Save Restaurant & Review'}alert('Metro Eats could not save this review. Your entries are still on screen.\n\n'+(e?.message||'Please try again.'))}}
function cancelSurvey(){pendingRestaurant=null;pendingReviewRestaurant=null;restaurantEditMode=false;closeModal()}
function showVisitHistory(id){let r=db.restaurants.find(x=>x.id===id);if(!r)return;let h=[...(r.reviewHistory||[])].reverse();modal.classList.add('show');modalBody.innerHTML=`<div class="eyebrow">Dining History</div><h2>${esc(r.name)}</h2><p class="hint">Each visit is kept as a separate review.</p><div class="visitHistory">${h.length?h.map((v,i)=>`<article class="visit"><div class="visitTop"><strong>Visit ${h.length-i}</strong><strong>${Number(v.overall||0).toFixed(1)}/10</strong></div>${stamp('Reviewed',v.createdAt)}<div class="small" style="margin-top:8px"><b>Ordered:</b> ${esc(v.ordered||'—')}</div><div class="small"><b>Order again:</b> ${esc(v.orderAgain||'—')}</div><div class="small" style="margin-top:8px">${topRatedSummary(v)}</div></article>`).join(''):'<div class="empty">No visit history yet.</div>'}</div><div class="actions"><button class="btn primary" onclick="closeModal();startSurvey('${r.id}')">Review Again</button><button class="btn danger" onclick="closeModal()">Close</button></div>`}
function showRankings(){let ranked=[...db.restaurants].filter(r=>r.survey).sort((a,b)=>(b.survey.overall||0)-(a.survey.overall||0));modal.classList.add('show');modalBody.innerHTML=`<div class="eyebrow">Dining Experience</div><h2>My Restaurant Rankings</h2><p class="hint">Rankings use only the 10 scored dining categories.</p>${ranked.length?`<div class="surveyGrid">${ranked.map((r,i)=>`<div class="surveyItem"><span class="rankBadge">#${i+1}</span><div><b>${esc(r.name)}</b><div class="small">${esc(r.location||'')} • <strong>${Number(r.survey.overall||0).toFixed(1)}/10</strong></div><div class="small">${topRatedSummary(r.survey)}</div>${stamp('Latest review',r.survey.createdAt)}</div><button class="btn" onclick="closeModal();startSurvey('${r.id}')">Review</button></div>`).join('')}</div>`:'<div class="empty">Complete a 10-question review to start your restaurant rankings.</div>'}<div class="actions"><button class="btn danger" onclick="closeModal()">Close</button></div>`}
function aiGuide(){let fav=db.recipes.filter(r=>r.favorite).map(r=>r.title).slice(0,10),visited=db.restaurants.map(r=>`${r.name} (${Number(r.rating||0).toFixed(1)}/5)`).slice(0,15),best=[...db.restaurants].filter(r=>r.survey).sort((a,b)=>b.survey.overall-a.survey.overall).slice(0,8).map(r=>`${r.name} (${r.survey.overall}/10)`),prompt=`I use an app called Metro Eats for recipes and a St. Louis / Metro East restaurant journal. Recommend 5 current restaurants that fit my tastes. Favorite recipes: ${fav.join(', ')||'none yet'}. Restaurants I have logged: ${visited.join(', ')||'none yet'}. My highest-rated visits: ${best.join(', ')||'none yet'}. Prefer restaurants I have not logged unless there is a strong reason. For each recommendation give current rating, cuisine, approximate price, why it fits, and the official website. Keep recommendations in St. Louis and the Metro East Illinois area.`;modal.classList.add('show');modalBody.innerHTML=`<div class="eyebrow">Personal Guide</div><h2>My Metro Eats Guide</h2><p class="hint">Your personal context is assembled below. Tap <b>Ask ChatGPT</b> to open ChatGPT with this brief, or copy it for another AI assistant.</p><div class="guideCard"><h4>What Metro Eats knows</h4><div class="tagRow">${fav.length?fav.slice(0,5).map(x=>`<span class="tag">${esc(x)}</span>`).join(''):'<span class="tag">No favorite recipes yet</span>'}</div><div class="small" style="margin-top:10px">${db.restaurants.length} saved restaurant${db.restaurants.length===1?'':'s'} • ${db.restaurants.reduce((n,r)=>n+(r.reviewHistory?.length||0),0)} visit reviews</div></div><div class="field" style="margin-top:12px"><label for="guidePrompt">Recommendation brief</label><textarea id="guidePrompt" rows="12">${esc(prompt)}</textarea></div><div class="actions"><button class="btn primary" onclick="askChatGPT()">✦ Ask ChatGPT</button><button class="btn" onclick="copyGuide()">Copy Brief</button><button class="btn danger" onclick="closeModal()">Close</button></div>`;window._guidePrompt=prompt}
function askChatGPT(){let u='https://chatgpt.com/?q='+encodeURIComponent(window._guidePrompt||'Recommend restaurants in St. Louis and Metro East.');window.open(u,'_blank','noopener')}
function copyGuide(){navigator.clipboard?.writeText(window._guidePrompt||'').then(()=>alert('Recommendation brief copied.')).catch(()=>alert('Copy is unavailable; select the text and copy it manually.'))}
function openBackup(){modal.classList.add('show');modalBody.innerHTML=`<div class="eyebrow">Metro Eats Backup</div><h2>Protect Your Journal</h2><p class="hint">Export your recipes, restaurant reviews, visit history, notes and photos to a backup file. You can restore it on this device later.</p><div class="backupGrid"><article class="featureCard"><div><h3>Export Backup</h3><p>Save a complete JSON backup of your current Metro Eats data.</p></div><button class="btn primary" onclick="exportBackup()">Export My Data</button></article><article class="featureCard"><div><h3>Restore Backup</h3><p>Replace the current local data with a Metro Eats backup file.</p></div><button class="btn" onclick="document.getElementById('restoreFile').click()">Choose Backup</button></article></div><div class="notice" style="margin-top:14px">Keep a backup somewhere safe. Browser storage can be cleared by iPhone or Safari settings.</div><div class="actions"><button class="btn danger" onclick="closeModal()">Close</button></div>`}
function exportBackup(){let payload={app:'Metro Eats',version:2,exportedAt:new Date().toISOString(),data:db},blob=new Blob([JSON.stringify(payload,null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='metro-eats-backup-'+new Date().toISOString().slice(0,10)+'.json';a.click();URL.revokeObjectURL(url)}
document.getElementById('restoreFile').addEventListener('change',async e=>{let f=e.target.files?.[0];if(!f)return;try{let data=JSON.parse(await f.text()),next=data.data||data;if(!Array.isArray(next.recipes)||!Array.isArray(next.restaurants))throw Error();if(!confirm('Restore this Metro Eats backup? Your current local data will be replaced.'))return;db=next;migrate();alert('Metro Eats backup restored.');closeModal();renderRecipes();renderRestaurants();updateStory()}catch{alert('That file is not a valid Metro Eats backup.')}e.target.value=''})
function updateStory(){let visits=db.restaurants.reduce((n,r)=>n+(r.reviewHistory?.length||0),0),favs=db.recipes.filter(r=>r.favorite).length;let v=document.getElementById('storyVisits'),f=document.getElementById('storyFavorites');if(v)v.textContent=visits;if(f)f.textContent=favs;let h=document.getElementById('storyHeadline');if(h)h.textContent=visits?`${visits} meal${visits===1?'':'s'} in your dining story.`:'A record of where you eat.'}
function closeModal(){modal.classList.remove('show');modalBody.innerHTML='';pendingRestaurant=null;pendingReviewRestaurant=null;window._editingPhotos=[];window._pendingImportedRecipe=null}
const newsLocalTerms=/\b(st\.?\s*louis|saint\s*louis|metro\s*east|alton|godfrey|east\s*alton|wood\s*river|bethalto|grafton|edwardsville|glen\s*carbon|granite\s*city|collinsville|belleville|fairview\s*heights|shiloh|o'?fallon|ofallon|maryville|pontoon\s*beach|roxana|highland|millstadt|waterloo|columbia|creve\s*coeur|university\s*city|maplewood|kirkwood|brentwood|central\s*west\s*end|soulard|cherokee\s*street|the\s*hill)\b/i;
const newsFoodTerms=/\b(restaurant|restaurants|dining|food|drink|bar|bars|brewery|breweries|brewpub|cafe|caf[eé]|coffee|chef|menu|menus|pizza|burger|burgers|breakfast|brunch|chicken|bbq|barbecue|dessert|ice\s*cream|taco|tacos|steak|seafood|bakery|baking|culinary|eatery|eateries|opens|opening|closes|closing|reopens|reopen|food\s*truck|hospitality|wine|cocktail|cocktails)\b/i;
const newsBadTerms=/\b(chicago|springfield|peoria|rockford|champaign|urbana|naperville|joliet|quad\s*cities|carbondale|decatur|indianapolis|kansas\s*city|nashville|new\s*york|los\s*angeles|miami|denver|seattle|portland|national|nationwide|travel|vacation|cruise|disney)\b/i;
function isLocalNews(x){let t=String(x.title||'');return newsFoodTerms.test(t)&&!newsBadTerms.test(t)&&(newsLocalTerms.test(t)||/^(Sauce Magazine|St\. Louis Magazine|The Telegraph|Belleville News-Democrat)$/.test(x.source||''))}
function dedupeNews(items){let s=new Set();return items.filter(x=>{let k=String(x.title||'').toLowerCase().replace(/[^a-z0-9]+/g,' ').trim();if(!k||s.has(k))return false;s.add(k);return isLocalNews(x)}).sort((a,b)=>new Date(b.date||0)-new Date(a.date||0))}
async function loadLocalNews(){let stampEl=document.getElementById('newsUpdated');if(stampEl)stampEl.textContent='Loading saved stories…';try{let r=await fetch('news.json?v='+Date.now(),{cache:'no-store'});if(!r.ok)throw Error();let data=await r.json(),items=dedupeNews(data.items||[]);renderLocalNews(items.length?items:fallbackNews,data.updated||'Saved')}catch{renderLocalNews(fallbackNews,'Saved stories')}}
function renderLocalNews(items,updated){let box=document.getElementById('newsGrid'),stampEl=document.getElementById('newsUpdated');box.innerHTML=items.length?items.slice(0,10).map(x=>`<article class="newsCard"><div class="newsSource">${esc(x.source||'Local publication')}</div><h4><a href="${esc(x.url||'#')}" target="_blank" rel="noopener noreferrer">${esc(x.title||'Local story')}</a></h4><a class="newsMore" href="${esc(x.url||'#')}" target="_blank" rel="noopener noreferrer">Read Full Story →</a><div class="newsDate">${esc(x.date||'')}</div></article>`).join(''):'<div class="empty">No local stories are available right now.</div>';if(stampEl)stampEl.textContent=updated&&updated!=='Saved stories'?'Updated '+new Date(updated).toLocaleString():'Showing saved stories'}
function registerSW(){if('serviceWorker' in navigator)navigator.serviceWorker.register('sw.js').catch(()=>{})}
renderRecipes();renderRestaurants();updateStory();loadLocalNews();registerSW();
