import {getState,updateState,id,average,restaurantScore} from "./store.js";
const app=document.querySelector("#app");
const nav=[["home","Home"],["restaurants","My Restaurants"],["recipes","My Recipes"],["insights","My Insights"]];
const categories=["Appetizers & Snacks","Breakfast & Brunch","Soups, Salads & Sandwiches","Main Dishes","Mexican & Latin","Italian","BBQ & Grilling","Side Dishes","Sauces, Gravies & Condiments","Bread & Baking","Desserts","Drinks","Other"];
const scores=[["overall","Overall Experience"],["food","Food Quality"],["menu","Menu & Selection"],["service","Service"],["atmosphere","Atmosphere"],["cleanliness","Cleanliness"],["value","Value for Money"],["drinks","Drinks & Bar"],["location","Location & Accessibility"],["returnScore","Would You Return?"]];
let page=(location.hash.slice(1)||"home");
function esc(s){return String(s||"").replace(/[&<>"']/g,function(c){return {"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[c]})}
function shell(active,body){return '<div class="app-shell"><header class="topbar"><div class="topbar-inner"><a class="brand" href="#home"><img src="../metro-eats-logo.png" alt="Metro Eats"></a><div class="top-actions"><button class="icon-button" data-action="search" aria-label="Search">⌕</button><button class="icon-button" data-action="settings" aria-label="Settings">⚙</button></div></div><div class="nav-wrap"><nav class="nav">'+nav.map(function(n){return '<button class="nav-button '+(active===n[0]?"active":"")+'" data-nav="'+n[0]+'">'+n[1]+"</button>"}).join("")+'</nav></div></header><main>'+body+"</main><div id="modal-root"></div></div>"}
function home(){const s=getState(),v=s.visits.slice(-3).reverse();return shell("home",'<section class="hero"><div class="eyebrow">Your food journal</div><h1>Eat well.<br>Remember it.</h1><p class="muted">A private record of the restaurants, meals and recipes that matter to you.</p></section><div class="grid grid-2"><button class="card action-card" data-action="review"><strong>Review a Restaurant</strong><span>Capture a visit in about two minutes.</span></button><button class="card action-card" data-action="recipe"><strong>Add a Recipe</strong><span>Keep recipes clean, editable and yours.</span></button></div><div class="section-head"><h2>Recent Visits</h2></div><section class="card">'+(v.length?'<div class="list">'+v.map(visitRow).join("")+'</div>':'<div class="empty">Your dining history will appear here.</div>')+'</section><div class="section-head"><h2>Around the Metro</h2></div><section class="card"><article class="news-item"><div class="eyebrow">St. Louis & Metro East</div><strong>Food news will live here.</strong><p class="muted">The 2.0 news module is intentionally isolated from the rest of the app.</p></article></section>')}
function visitRow(v){const r=getState().restaurants.find(function(x){return x.id===v.restaurantId});return '<div class="list-row"><div><strong>'+esc(r?r.name:"Restaurant")+'</strong><div class="muted">'+esc(v.meal||"Visit")+"</div></div><span class="score">"+(v.overall?Number(v.overall).toFixed(1):"—")+'<small>/10</small></span></div>'}
function restaurants(){const s=getState(),rs=s.restaurants.slice().sort(function(a,b){return (restaurantScore(b.id)||-1)-(restaurantScore(a.id)||-1)});return shell("restaurants",'<section class="hero"><div class="eyebrow">My Restaurants</div><h1>Your dining history.</h1><p class="muted">Restaurants and visits remain separate, connected records.</p></section><div class="section-head"><h2>Restaurants</h2><button class="btn gold" data-action="review">Rate This Restaurant</button></div><section class="card"><div class="list">'+(rs.length?rs.map(function(r){return '<button class="list-row" style="width:100%;border:0;background:none;text-align:left" data-restaurant="'+r.id+'"><div><strong>'+esc(r.name)+'</strong><div class="muted">'+esc([r.street,r.city,r.state].filter(Boolean).join(", "))+'</div></div><span class="score">'+(restaurantScore(r.id)?restaurantScore(r.id).toFixed(1):"—")+'<small>/10</small></span></button>'}).join(""):'<div class="empty">No restaurants yet. Start with your next meal.</div>')+"</div></section>")}
function recipes(){const s=getState(),rs=s.recipes.slice().sort(function(a,b){return String(b.updatedAt).localeCompare(String(a.updatedAt))});return shell("recipes",'<section class="hero"><div class="eyebrow">My Recipes</div><h1>Recipes worth keeping.</h1><p class="muted">One standard editor for manual recipes and future imports.</p></section><div class="section-head"><h2>Recipes</h2><button class="btn gold" data-action="recipe">Add Recipe</button></div><section class="card"><div class="list">'+(rs.length?rs.map(function(r){return '<button class="list-row" style="width:100%;border:0;background:none;text-align:left" data-recipe="'+r.id+'"><div><strong>'+esc(r.name)+'</strong><div class="muted">'+esc(r.category||"Uncategorized")+'</div></div><span>›</span></button>'}).join(""):'<div class="empty">No recipes yet.</div>')+"</div></section>")}
function insights(){const s=getState(),vals=s.visits.map(function(v){return Number(v.overall)});return shell("insights",'<section class="hero"><div class="eyebrow">My Insights</div><h1>See your food story.</h1><p class="muted">Your data stays personal and separate from outside ratings.</p></section><div class="grid grid-3"><div class="card"><div class="eyebrow">Visits</div><div class="score">'+s.visits.length+"</div></div><div class="card"><div class="eyebrow">Restaurants</div><div class="score">"+s.restaurants.length+"</div></div><div class="card"><div class="eyebrow">Average Visit</div><div class="score">"+(average(vals.filter(Number.isFinite))||"—")+'<small>/10</small></div></div></div><div class="section-head"><h2>Foundation</h2></div><section class="card"><p class="muted">Restaurants, Food and Trends can grow independently from the shared data layer.</p></section>')}
function modal(body){document.querySelector("#modal-root").innerHTML='<div class="modal-backdrop"><section class="modal" role="dialog" aria-modal="true">'+body+"</section></div>"}
function reviewModal(prefill){const fs=scores.map(function(x){return '<div class="field"><label>'+x[1]+'</label><select name="'+x[0]+'"><option value="">Select 1–10</option>'+Array.from({length:10},function(_,i){return '<option value="'+(i+1)+'">'+(i+1)+"</option>"}).join("")+"</select></div>"}).join("");return '<div class="modal-head"><h2>Rate This Restaurant</h2><button class="icon-button" data-action="close">×</button></div><form id="review-form" class="form"><div class="field"><label>Restaurant</label><input name="restaurantName" required value="'+esc(prefill||"")+'"></div><div class="grid grid-2">'+fs+'</div><div class="field"><label>What Did You Order?</label><textarea name="order" placeholder="Food items only"></textarea></div><div class="field"><label>Would You Order It Again?</label><select name="again"><option value="">Select</option><option>Yes</option><option>No</option></select></div><div class="form-actions"><button type="button" class="btn secondary" data-action="close">Cancel</button><button class="btn gold">Save Review</button></div></form>'}
function recipeModal(r){r=r||{};return '<div class="modal-head"><h2>'+(r.id?"Edit":"Add")+' Recipe</h2><button class="icon-button" data-action="close">×</button></div><form id="recipe-form" class="form"><input type="hidden" name="id" value="'+esc(r.id||"")+'"><div class="field"><label>Recipe Name</label><input name="name" required value="'+esc(r.name||"")+'"></div><div class="grid grid-2"><div class="field"><label>Category</label><select name="category"><option value="">Select category</option>'+categories.map(function(c){return '<option '+(r.category===c?"selected":"")+'>'+esc(c)+"</option>"}).join("")+'</select></div><div class="field"><label>Subcategory</label><input name="subcategory" value="'+esc(r.subcategory||"")+'"></div></div><div class="grid grid-2"><div class="field"><label>Servings</label><input name="servings" value="'+esc(r.servings||"")+'"></div><div class="field"><label>Total Time</label><input name="time" value="'+esc(r.time||"")+'"></div></div><div class="field"><label>Ingredients</label><textarea name="ingredients" required>'+esc(r.ingredients||"")+'</textarea></div><div class="field"><label>Directions</label><textarea name="directions" required>'+esc(r.directions||"")+'</textarea></div><div class="field"><label>Notes</label><textarea name="notes">'+esc(r.notes||"")+'</textarea></div><div class="form-actions"><button type="button" class="btn secondary" data-action="close">Cancel</button><button class="btn gold">Save Recipe</button></div></form>'}
function searchModal(){modal('<div class="modal-head"><h2>Search Metro Eats</h2><button class="icon-button" data-action="close">×</button></div><div class="field"><label>Search everything</label><input id="global-search" autofocus placeholder="Restaurants, visits, recipes"></div><div id="search-results" class="list"></div>')}
function settingsModal(){modal('<div class="modal-head"><h2>Settings</h2><button class="icon-button" data-action="close">×</button></div><p class="muted">Private by default. Backup, export and migration remain isolated services.</p><div class="form-actions"><button class="btn secondary" data-action="close">Close</button></div>')}
function render(){const views={home:home,restaurants:restaurants,recipes:recipes,insights:insights};app.innerHTML=views[page]?views[page]():views.home();window.scrollTo(0,0)}
function close(){document.querySelector("#modal-root").innerHTML=""}
app.addEventListener("click",function(e){const n=e.target.closest("[data-nav]");if(n){location.hash=n.dataset.nav;return}const a=e.target.closest("[data-action]");if(a){if(a.dataset.action==="review")modal(reviewModal());if(a.dataset.action==="recipe")modal(recipeModal());if(a.dataset.action==="search")searchModal();if(a.dataset.action==="settings")settingsModal();if(a.dataset.action==="close")close();return}const r=e.target.closest("[data-restaurant]");if(r){const x=getState().restaurants.find(function(v){return v.id===r.dataset.restaurant});if(x)modal(reviewModal(x.name))}const q=e.target.closest("[data-recipe]");if(q){const x=getState().recipes.find(function(v){return v.id===q.dataset.recipe});if(x)modal(recipeModal(x))}});
app.addEventListener("submit",function(e){e.preventDefault();const f=e.target;if(f.id==="review-form"){const d=new FormData(f),name=String(d.get("restaurantName")||"").trim(),now=new Date().toISOString();updateState(function(s){let r=s.restaurants.find(function(x){return x.name.toLowerCase()===name.toLowerCase()});if(!r){r={id:id("rest"),name:name};s.restaurants.push(r)}const v={id:id("visit"),restaurantId:r.id,createdAt:now,meal:"Visit",order:String(d.get("order")||""),orderAgain:String(d.get("again")||"")};scores.forEach(function(x){const n=Number(d.get(x[0]));v[x[0]]=Number.isFinite(n)?n:null});s.visits.push(v)});close();render()}if(f.id==="recipe-form"){const d=new FormData(f),now=new Date().toISOString();updateState(function(s){const rid=String(d.get("id")||"");let r=s.recipes.find(function(x){return x.id===rid});const data={name:String(d.get("name")||"").trim(),category:String(d.get("category")||""),subcategory:String(d.get("subcategory")||""),servings:String(d.get("servings")||""),time:String(d.get("time")||""),ingredients:String(d.get("ingredients")||""),directions:String(d.get("directions")||""),notes:String(d.get("notes")||""),updatedAt:now};if(r)Object.assign(r,data);else s.recipes.push(Object.assign({id:id("recipe")},data))});close();render()}});
window.addEventListener("hashchange",function(){page=location.hash.slice(1)||"home";render()});
render();